spring:
  config:
    activate:
      on-profile: lab-cloud
    import: optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  cloud:
    config:
      enabled: ${SPRING_CLOUD_CONFIG_ENABLED:true}
    discovery:
      enabled: true
    loadbalancer:
      enabled: true
  application:
    name: ${SPRING_APPLICATION_NAME:corebank-payment-lab}

eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

investigation:
  payment-service:
    base-url: ${INVESTIGATION_PAYMENT_BASE_URL:http://corebank-payment-lab}
